import type { Metadata } from "next";
import { Geist, Geist_Mono, K2D } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/auth/SessionProviders"
import Link from "next/link";
import Image from "next/image";

const k2d = K2D({
  weight: "100",
  subsets: ["latin"]
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en" className="bg-[#1A1A1A]">
      <body
        className={`${k2d.className} antialiased` } 
      >
        <SessionProvider session={session}>
          <div className="bg-[#1A1A1A] min-h-screen text-[white] py-[20px]">
            <div className="bg-[#2D2D2D] mx-[20px] px-[50px] py-[24px] rounded-[20px] flex justify-between items-center mb-[80px]">
              <div className="">
                <Link className="flex text-[40px] fw-[700] font-bold" href="/">Tech <Image width={70} height={65} className="px-[5px]" src="img/logo.svg" alt="" />Tinker</Link>
              </div>
              <div className="text-[18px] font-bold">
                <Link className="bg-[#FFCC70] px-[45px] py-[10px] text-[#1A1A1A] rounded-[15px]" href="/signin">
                  Sign In
                </Link>
                <Link className="ml-[50px]" href="/signup">
                  Sign Up
                </Link>
              </div>
            </div>
            <div className="max-w-[1200px] m-auto ">
              {children}
            </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
